package com.sugarmunch.app.ui.customization.manager

import com.sugarmunch.app.ui.customization.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.util.UUID

/**
 * EXTREME Preset Engine for SugarMunch
 * Manages smart presets, contextual triggers, and AI-powered suggestions
 */
class PresetEngine(
    private val customizationRepository: CustomizationRepository
) {
    private val mutex = Mutex()

    private val _presets = MutableStateFlow<List<PresetConfig>>(emptyList())
    val presets: StateFlow<List<PresetConfig>> = _presets.asStateFlow()

    private val _activePresetId = MutableStateFlow<String?>(null)
    val activePresetId: StateFlow<String?> = _activePresetId.asStateFlow()

    /**
     * Initialize preset engine
     */
    suspend fun initialize() {
        mutex.withLock {
            _presets.value = customizationRepository.presetConfigsFlow.value
            observePresets()
        }
    }

    private suspend fun observePresets() {
        customizationRepository.presetConfigsFlow.collect { presets ->
            _presets.value = presets
        }
    }

    /**
     * Create a new preset
     */
    suspend fun createPreset(
        name: String,
        description: String = "",
        category: PresetCategory = PresetCategory.CUSTOM,
        backgroundConfig: BackgroundConfig? = null,
        colorProfile: ColorProfile? = null,
        animationProfile: AnimationProfile? = null,
        effectConfigs: Map<String, EffectConfig>? = null,
        particleConfig: ParticleConfig? = null
    ): PresetConfig {
        return mutex.withLock {
            val preset = PresetConfig(
                id = UUID.randomUUID().toString(),
                name = name,
                description = description,
                category = category,
                backgroundConfig = backgroundConfig,
                colorProfile = colorProfile,
                animationProfile = animationProfile,
                effectConfigs = effectConfigs,
                particleConfig = particleConfig,
                isAutoGenerated = false,
                usageCount = 0,
                lastUsedAt = null,
                rating = 0f
            )

            val newPresets = _presets.value + preset
            customizationRepository.savePresetConfigs(newPresets)
            preset
        }
    }

    /**
     * Update an existing preset
     */
    suspend fun updatePreset(preset: PresetConfig) {
        mutex.withLock {
            val newPresets = _presets.value.map {
                if (it.id == preset.id) preset else it
            }
            customizationRepository.savePresetConfigs(newPresets)
        }
    }

    /**
     * Delete a preset
     */
    suspend fun deletePreset(presetId: String) {
        mutex.withLock {
            if (_activePresetId.value == presetId) {
                _activePresetId.value = null
            }
            val newPresets = _presets.value.filter { it.id != presetId }
            customizationRepository.savePresetConfigs(newPresets)
        }
    }

    /**
     * Activate a preset
     */
    suspend fun activatePreset(presetId: String) {
        mutex.withLock {
            val preset = _presets.value.find { it.id == presetId }
            if (preset != null) {
                _activePresetId.value = presetId

                // Update usage stats
                val updated = preset.copy(
                    usageCount = preset.usageCount + 1,
                    lastUsedAt = System.currentTimeMillis()
                )
                updatePreset(updated)

                // Apply preset settings
                applyPreset(preset)
            }
        }
    }

    /**
     * Apply preset configurations
     */
    private suspend fun applyPreset(preset: PresetConfig) {
        preset.backgroundConfig?.let { customizationRepository.saveBackgroundConfig(it) }
        preset.colorProfile?.let { customizationRepository.saveColorProfile(it) }
        preset.animationProfile?.let { customizationRepository.saveAnimationProfile(it) }
        preset.particleConfig?.let { customizationRepository.saveParticleConfig(it) }

        if (preset.effectConfigs?.isNotEmpty() == true) {
            customizationRepository.saveEffectConfigs(preset.effectConfigs)
        }
    }

    /**
     * Add context trigger to preset
     */
    suspend fun addContextTrigger(
        presetId: String,
        trigger: ContextTrigger
    ) {
        mutex.withLock {
            val preset = _presets.value.find { it.id == presetId }
            if (preset != null) {
                val updated = preset.copy(
                    contextTriggers = preset.contextTriggers + trigger
                )
                updatePreset(updated)
            }
        }
    }

    /**
     * Remove context trigger from preset
     */
    suspend fun removeContextTrigger(
        presetId: String,
        triggerIndex: Int
    ) {
        mutex.withLock {
            val preset = _presets.value.find { it.id == presetId }
            if (preset != null) {
                val triggers = preset.contextTriggers.toMutableList()
                if (triggerIndex in triggers.indices) {
                    triggers.removeAt(triggerIndex)
                    val updated = preset.copy(contextTriggers = triggers)
                    updatePreset(updated)
                }
            }
        }
    }

    /**
     * Rate a preset
     */
    suspend fun ratePreset(presetId: String, rating: Float) {
        mutex.withLock {
            val preset = _presets.value.find { it.id == presetId }
            if (preset != null) {
                val updated = preset.copy(rating = rating.coerceIn(0f, 5f))
                updatePreset(updated)
            }
        }
    }

    /**
     * Get presets by category
     */
    fun getPresetsByCategory(category: PresetCategory): List<PresetConfig> {
        return _presets.value.filter { it.category == category }
    }

    /**
     * Get auto-generated presets
     */
    fun getAutoGeneratedPresets(): List<PresetConfig> {
        return _presets.value.filter { it.isAutoGenerated }
    }

    /**
     * Get presets with context triggers
     */
    fun getContextualPresets(): List<PresetConfig> {
        return _presets.value.filter { it.contextTriggers.isNotEmpty() }
    }

    /**
     * Search presets
     */
    fun searchPresets(query: String): List<PresetConfig> {
        if (query.isBlank()) return _presets.value
        return _presets.value.filter {
            it.name.contains(query, ignoreCase = true) ||
            it.description.contains(query, ignoreCase = true)
        }
    }

    /**
     * Check and activate contextual presets based on current context
     */
    suspend fun checkContextualTriggers(
        batteryLevel: Int? = null,
        isCharging: Boolean? = null,
        hourOfDay: Int? = null,
        currentApp: String? = null,
        isWifiConnected: Boolean? = null,
        isBluetoothConnected: Boolean? = null,
        isDoNotDisturb: Boolean? = null
    ) {
        val contextualPresets = getContextualPresets()

        contextualPresets.forEach { preset ->
            preset.contextTriggers.forEach { trigger ->
                val shouldActivate = when (trigger.type) {
                    ContextType.TIME -> hourOfDay?.let { checkTimeTrigger(it, trigger) } ?: false
                    ContextType.BATTERY -> batteryLevel?.let { checkBatteryTrigger(it, trigger) } ?: false
                    ContextType.CHARGING -> isCharging?.let { checkChargingTrigger(it, trigger) } ?: false
                    ContextType.APP -> currentApp?.let { checkAppTrigger(it, trigger) } ?: false
                    ContextType.WIFI -> isWifiConnected?.let { checkWifiTrigger(it, trigger) } ?: false
                    ContextType.BLUETOOTH -> isBluetoothConnected?.let { checkBluetoothTrigger(it, trigger) } ?: false
                    ContextType.DO_NOT_DISTURB -> isDoNotDisturb?.let { checkDndTrigger(it, trigger) } ?: false
                    ContextType.LOCATION -> false // Location requires more complex handling
                }

                if (shouldActivate) {
                    when (trigger.action) {
                        ContextAction.ACTIVATE -> activatePreset(preset.id)
                        ContextAction.DEACTIVATE -> if (_activePresetId.value == preset.id) _activePresetId.value = null
                        ContextAction.TOGGLE -> if (_activePresetId.value == preset.id) {
                            _activePresetId.value = null
                        } else {
                            activatePreset(preset.id)
                        }
                    }
                }
            }
        }
    }

    private fun checkTimeTrigger(hourOfDay: Int, trigger: ContextTrigger): Boolean {
        val triggerHour = trigger.value.toIntOrNull() ?: return false
        return hourOfDay == triggerHour
    }

    private fun checkBatteryTrigger(batteryLevel: Int, trigger: ContextTrigger): Boolean {
        val triggerLevel = trigger.value.toIntOrNull() ?: return false
        return batteryLevel <= triggerLevel
    }

    private fun checkChargingTrigger(isCharging: Boolean, trigger: ContextTrigger): Boolean {
        return isCharging == (trigger.value.toBoolean())
    }

    private fun checkAppTrigger(currentApp: String, trigger: ContextTrigger): Boolean {
        return currentApp == trigger.value
    }

    private fun checkWifiTrigger(isWifiConnected: Boolean, trigger: ContextTrigger): Boolean {
        return isWifiConnected == (trigger.value.toBoolean())
    }

    private fun checkBluetoothTrigger(isBluetoothConnected: Boolean, trigger: ContextTrigger): Boolean {
        return isBluetoothConnected == (trigger.value.toBoolean())
    }

    private fun checkDndTrigger(isDoNotDisturb: Boolean, trigger: ContextTrigger): Boolean {
        return isDoNotDisturb == (trigger.value.toBoolean())
    }

    /**
     * Generate AI-powered preset suggestions based on usage patterns
     */
    suspend fun generateAiSuggestions(
        usagePatterns: Map<String, Int>,
        currentSettings: Map<String, Any>
    ): List<PresetConfig> {
        val suggestions = mutableListOf<PresetConfig>()

        // Analyze most used settings
        val topUsedCategories = usagePatterns.entries
            .sortedByDescending { it.value }
            .take(3)

        // Generate suggestions based on patterns
        topUsedCategories.forEach { (category, count) ->
            val suggestion = PresetConfig(
                id = UUID.randomUUID().toString(),
                name = "Suggested: $category",
                description = "Based on your usage patterns",
                category = PresetCategory.CUSTOM,
                isAutoGenerated = true,
                rating = 4.5f
            )
            suggestions.add(suggestion)
        }

        return suggestions
    }

    /**
     * Export preset to JSON string
     */
    suspend fun exportPreset(presetId: String): String {
        val preset = _presets.value.find { it.id == presetId }
            ?: throw IllegalArgumentException("Preset not found: $presetId")

        return kotlinx.serialization.json.Json {
            ignoreUnknownKeys = true
            isLenient = true
        }.encodeToString(PresetConfig.serializer(), preset)
    }

    /**
     * Import preset from JSON string
     */
    suspend fun importPreset(jsonString: String): PresetConfig {
        val preset = kotlinx.serialization.json.Json {
            ignoreUnknownKeys = true
            isLenient = true
        }.decodeFromString(PresetConfig.serializer(), jsonString)

        val newPreset = preset.copy(
            id = UUID.randomUUID().toString(),
            isAutoGenerated = false
        )

        val newPresets = _presets.value + newPreset
        customizationRepository.savePresetConfigs(newPresets)
        return newPreset
    }

    /**
     * Merge similar presets
     */
    suspend fun mergePresets(presetIds: List<String>, mergedName: String): PresetConfig? {
        if (presetIds.size < 2) return null

        val presetsToMerge = _presets.value.filter { it.id in presetIds }
        if (presetsToMerge.size != presetIds.size) return null

        // Merge configurations (take first non-null value for each setting)
        val merged = PresetConfig(
            id = UUID.randomUUID().toString(),
            name = mergedName,
            description = "Merged from ${presetsToMerge.size} presets",
            category = presetsToMerge.first().category,
            backgroundConfig = presetsToMerge.firstNotNullOfOrNull { it.backgroundConfig },
            colorProfile = presetsToMerge.firstNotNullOfOrNull { it.colorProfile },
            animationProfile = presetsToMerge.firstNotNullOfOrNull { it.animationProfile },
            effectConfigs = presetsToMerge.firstNotNullOfOrNull { it.effectConfigs },
            particleConfig = presetsToMerge.firstNotNullOfOrNull { it.particleConfig },
            isAutoGenerated = false
        )

        // Remove old presets and add merged
        val newPresets = (_presets.value - presetsToMerge) + merged
        customizationRepository.savePresetConfigs(newPresets)

        return merged
    }

    /**
     * Archive unused presets
     */
    suspend fun archiveUnusedPresets(daysThreshold: Int = 30) {
        val thresholdTime = System.currentTimeMillis() - (daysThreshold * 24 * 60 * 60 * 1000L)

        val unusedPresets = _presets.value.filter { preset ->
            preset.lastUsedAt == null || preset.lastUsedAt!! < thresholdTime
        }

        // Mark as archived by adding to description
        unusedPresets.forEach { preset ->
            if (!preset.description.contains("[ARCHIVED]")) {
                updatePreset(
                    preset.copy(
                        description = "[ARCHIVED] ${preset.description}"
                    )
                )
            }
        }
    }
}
